### ISSUE TITLE
I think you can merge `archives` page to `index` page. 

### ISSUE THREAD

**Issue by ShuYuMo2003** [sshwy/hexo-theme-essence#12]
I think you can merge `archives` page to `index` page. 

In my opinion, the layout of `archives` page is much more comfortable than the layout of `index` page.

QAQ. do you think so?

**Comment by sshwy** [comment]
我寻思咱们可以说中文 🤔 
其实index页我也不太会设计 但我觉得一个博客还是得有一个index页
一上来就是三列文章列表可能不太好，显得没有门户

**Comment by ShuYuMo2003** [comment]
哇 作者是中国人！ (大雾)

做宽一点也会更好看些吧，这样显得好挤…

主页本来就是一个提供简略信息的页面吧，感觉这样有点难受。

主要是我真心喜欢这个主题 /kel 不是很熟这个模板语言 比较想要一个特别简洁的主题 

本来是想就直接 Typora 生成 html 然后主页挂几个 link 就完事了，但是感觉有点草率…而且不是很敢花时间写…就一直咕咕咕了

打算用黄队的主题，提几个我的意见，黄队要是觉得不行我之后 fork 了自己改改试试 /kel /cy.

**Comment by sshwy** [comment]
是说主页的headline下面整个分栏的列表吗
这个可以有 👍

**Comment by ShuYuMo2003** [comment]
是的啊 这个可以直接粘的吧

**Comment by sshwy** [comment]
主要是 快要WC了 主题开发就有点滞后（

**Comment by ShuYuMo2003** [comment]
主要是 快要WC了 博客都停更了（（（ me

**Comment by sshwy** [comment]
你可以整个 feature request list 等打完wc我来佛系开发一下 🌚

**Comment by ShuYuMo2003** [comment]
等我干完 WC 可以一起开发 /kel /kel /kel 🌚🌚🌚

**Comment by sshwy** [comment]
好！

**Comment by sshwy** [comment]
已经merge了
现在有推荐文章和最近更新两个option
